### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Leymooo** [True-Games/TickOptimizer#6]
[06:59:55 INFO]: [TickOptimizer] Loading TickOptimizer v1.0
[06:59:55 WARN]: java.lang.NoSuchFieldError: REGISTRY
[06:59:55 WARN]:        at tickoptimizer.ServerInjector.fixDispenserRegistry(ServerInjector.java:149)
[06:59:55 WARN]:        at tickoptimizer.ServerInjector.injectRegistry(ServerInjector.java:81)
[06:59:55 WARN]:        at tickoptimizer.TickOptimizer.onLoad(TickOptimizer.java:16)
[06:59:55 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:296)
[06:59:55 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[06:59:55 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[06:59:55 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by Shevchik** [comment]
You are not using a supported spigot 1.8.8 build.
This plugin is dead anyway now, because i'm going to create my own version of spigot with those improvements.

**Comment by Leymooo** [comment]
@Shevchik 
А примерно через сколько Вы это сделаете?

**Comment by Leymooo** [comment]
@Shevchik 
Может баг, может нет. Но после того как я обновил этот плагин, сервер не может нормально остановится, зависает на [Server thread/INFO]: Saving chunks for level 'world'/Overworld
и всё. И так на целый час зависло. И так на 2 двух серверах по 2-3 раза было за сегодня, убрал плагин и начал сервер нормально останавливаться. 
Надеюсь увидишь это.
